CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER,
    MEMBER_ID VARCHAR2(30),
    MAMBER_PW VARCHAR2(30),
    MEMBER_NAME VARCHAR2(15),
    MEMBER_EMAIL VARCHAR2(50),
    MEBMER_PHONE VARCHAR2(15),
    MEBMER_DATE DATE
);

CREATE TABLE BOARD
(
    BOARD_NO NUMBER,
    BOARD_TITLE VARCHAR2(1000),
    BOARD_CONTENT VARCHAR2(4000),
    BOARD_HIT NUMBER,
    BOARD_DATE DATE
);

CREATE TABLE MANUFACTURER
(
    MANUFACTURER_NO VARCHAR2(12),
    MANUFACTURER_NAME VARCHAR2(100),
    MANUFACTURER_PHONE VARCHAR2(15)
);

CREATE TABLE WAREHOUSE
(
    WAREHOUSE_NO NUMBER,
    WAREHOUSE_NAME VARCHAR2(5),
    WAREHOUSE_LOCATION VARCHAR2(100),
    WAREHOUSE_USED VARCHAR2(1)
);

CREATE TABLE DELIVERY_SERVICE
(
    DELIVERY_SERVICE_NO VARCHAR2(12),
    DELIVERY_SERVICE_NAME VARCHAR2(20),
    DELIVERY_SERVICE_PHONE VARCHAR2(15),
    DELIVERY_SERVICE_ADDRESS VARCHAR2(100)
);

CREATE TABLE DELIVERY
(
    DELIVERY_NO NUMBER,
    DELIVERY_SERVICE VARCHAR2(12),
    DELIVERY_PRICE NUMBER,
    DELIVERY_DATE DATE
);

CREATE TABLE ORDERS
(
    ORDERS_NO NUMBER,
    MEMBER_NO NUMBER,
    DELIVERY_NO NUMBER,
    ORDERS_PAY VARCHAR2(10),
    ORDERS_DATE DATE
);

CREATE TABLE PRODUCT
(
    PRODUCT_CODE VARCHAR2(10),
    PRODUCT_NAME VARCHAR2(50),
    PRODUCT_PRICE NUMBER,
    PRODUCT_CATEGORY VARCHAR2(15),
    ORDERS_NO NUMBER,
    MANUFACTURER_NO VARCHAR2(12),
    WAREHOUSE_NO NUMBER
);

ALTER TABLE BANK ADD CONSTRAINT CUSTOMER_BANK_FK FOREIGN KEY(BANK_CODE) REFERENCES BANK(BANK_CODE);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(BOARD_NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEBMER_NO);

DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE DELIVERY;
DROP TABLE DELIVERY_SERVICE;
DROP TABLE WAREHOUSE;
DROP TABLE MANUFACTURER;
DROP TABLE BOARD;
DROP TABLE MEMBER;



    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    